#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to yo##r load-balancer IP (lb-01). Let’s also add other
#subdomains to make our life easier, and write a Bash script that will display information about subdomains.

url=$(dig +short "$2.$1" | awk "NR==1")
ip_1=$(dig +short www.fridausokoya.tech | awk "NR==1")
ip_2=$(dig +short lb-01.fridausokoya.tech | awk "NR==1")
ip_3=$(dig +short web-01.fridausokoya.tech | awk "NR==1")
ip_4=$(dig +short web-02.fridausokoya.tech | awk "NR==1")

check_domain () {
    if [ "$#" -eq 2 ]
    then
        echo "The Subdomain $2 is a A record and points to $url"
    elif [ "$#" -eq 1 ]
    then
        echo "The Subdomain www is a A record and points to $ip_1"
        echo "The Subdomain lb-01 is a A record and points to $ip_2"
        echo "The Subdomain web-01 is a A record and points to $ip_3"
        echo "The Subdomain web-02 is a A record and points to $ip_4"
    fi
}

check_domain "$@"
