#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to yo##r load-balancer IP (lb-01). Let’s also add other
#subdomains to make our life easier, and write a Bash script that will display information about subdomains.
subdomains=("www" "lb-01" "web-01" "web-02")

display () {
    INFO=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    RECORD_TYPE=$(echo "$INFO" | awk '{print $4}')
    DESTINATION=$(echo "$INFO" | awk '{print $5}')
    echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
}

check_domain () {
    if [ "$#" -eq 2 ]
    then
        display "$1" "$2"
    elif [ "$#" -eq 1 ]
    then
        for sub in "${subdomains[@]}"
        do
            display "$1" "$sub"
        done
    fi
}

check_domain "$@"
