#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

#install nginx
sudo apt update && sudo apt install -y nginx > /dev/null
#switch to root user for administrative privilege
#start nginx
sudo service nginx start
#copy test to the file
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
text="\tlocation \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}\n}"
location="/etc/nginx/sites-available/default"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available
sed -i -r "s/^}$/$text/" "$location"
sudo chown -R root:root /var/www/html
sudo chown -R root:root /etc/nginx/sites-available
#restart nginx
sudo service nginx reload
