#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

#install nginx
#sudo apt update -y && sudo apt install -y nginx
#switch to root user for administrative privilege
#start nginx
sudo service nginx start
#copy test to the file
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html
text="\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}\n}"
location="/etc/nginx/sites-available/default_1"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available
sed -i -r "s/^}$/$text/" "$location"
echo "Ceci n'est pas une page" > /var/www/html/404.html
error="\terror_page 404 \/404.html;"
sed -i "48i\\$error" "$location"
header="\t\tadd_header X-Served-By $HOSTNAME;\n\t}"
sed -i -r "s/^\t}$/$header/" "$location"
sudo chown -R root:root /var/www/html
sudo chown -R root:root /etc/nginx/sites-available
#restart nginx
sudo service nginx reload
