#!/usr/bin/env bash
#install and configure load balancer

sudo apt update -y
sudo apt upgrade -y
sudo apt install haproxy -y
sudo service haproxy start
file='/etc/haproxy/haproxy.cfg'
chown -R "$USER":"$USER" /etc/haproxy
content="
frontend haproxy-main
    bind *:80
    default_backend webservers

backend webservers
    server 222478-web-01 52.91.137.18:80 check
    server 222478-web-02 54.174.194.46:80 check
"
echo "$content" >> "$file"
chown -R root:root /etc/haproxy
sudo service haproxy reload
