#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates 
#itself when receiving a SIGQUIT or SIGTERM signal

function sigint()
{
	echo "Y U no love me?!"
}

function sig_quit_term()
{
	sudo rm /var/run/myscript.pid
	echo "I hate the kill command"
	exit
}

trap sig_quit_term SIGTERM

trap sig_quit_term SIGQUIT

trap sigint SIGINT

sudo touch /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
done
