#!/usr/bin/bash
#Tell the story of passwd

while IFS=':' read -r user x gid uid info home shell
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $info"
done < /etc/passwd
