#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

for file in *
do
	if [[ $file != .* ]]
	then	
		part_after_dash=$(echo "$file" | cut -d '-' -f 2)
		echo "$part_after_dash"
	fi
done
