#!/usr/bin/env bash
# changes home IP

sudo chmod o+w /etc/hosts

sed  's/127.0.0.1/127.0.0.2/g' /etc/hosts > file

sudo mv file /etc/hosts

sed '/8.8.8.8/d' /etc/hosts > file

sudo mv file /etc/hosts

echo "8.8.8.8    facebook.com" >> /etc/hosts

sudo chmod o-w /etc/hosts
